services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    ports:
      - "3001:3000"
  deamon:
    image: getportal/sdk-daemon:latest
    container_name: daemon
    restart: unless-stopped
    ports:
      - "3002:3000"
    env_file:
      - ./backend/.env
  mint:
    image: getportal/cdk-mintd:latest
    container_name: mint
    restart: unless-stopped
    ports:
      - "3003:8085"
